### ISSUE TITLE
publish uDepot code

### ISSUE THREAD

**Issue by spacejam** [ibm-research/uDepot#1]
Hello, is the code for uDepot going to be made available for those seeking to reproduce its impressive results?

**Comment by nik-io** [comment]
Hi, thank you for the interest!
We are currently going through the internal approval process to open source uDepot and, assuming it is cleared, the code is going to be published in this repo as soon as possible.

**Comment by spacejam** [comment]
@nikolas-ioannou It's great to hear that effort is being spent to open source it! I'm really looking forward to reading and profiling it, so thank you to all those who are working on getting it through the process and making the research reproducible :]

**Comment by nphase** [comment]
@nik-io after reading the uDepot white paper, I too am interested in seeing the source code. Are there any plans of releasing?

**Comment by nik-io** [comment]
@spacejam @nphase: fyi, we have just released the uDepot code here: https://github.com/IBM/uDepot. Hope you are still interested in having a look! thanks
